logsBucket: gs://gcloud-build-python-image-build-logs

steps:
  - name: python:3.13.12-alpine3.23
    entrypoint: pip3
    args: ['install', '-r', 'requirements.txt']

  - name: python:3.13.12-alpine3.23
    entrypoint: pytest
    args: ['tests/*.py']
