logsBucket: gs://gcloud-build-python-image-build-logs

steps:
  - name: python:3.13.12-alpine3.23
    id: Create virtual environment
    entrypoint: python
    args: ['-m', 'venv', '.venv']

  - name: python:3.13.12-alpine3.23
    id: Install project dependencies
    entrypoint: .venv/bin/pip3
    args: ['install','-r','requirements.txt']

  - name: python:3.13.12-alpine3.23
    id: Performe PyTests
    entrypoint: .venv/bin/pytest
    args: ['tests/']

  - name: gcr.io/cloud-builders/docker
    id: Build container image
    args:
      - build
      - -t
      - us-south1-docker.pkg.dev/venturini-brazil/flask-app/web-api:$BUILD_ID
      - -t
      - us-south1-docker.pkg.dev/venturini-brazil/flask-app/web-api:latest
      - .

  - name: gcr.io/cloud-builders/docker
    id: Store container image
    args:
      - push
      - us-south1-docker.pkg.dev/venturini-brazil/flask-app/web-api:$BUILD_ID
      - us-south1-docker.pkg.dev/venturini-brazil/flask-app/web-api:latest

  - name: gcr.io/cloud-builders/gcloud
    id: Deploy into Cloud Engine
    entrypoint: bash
    args:
      - -c
      - |
        # why can't I ssh without specifying zone?
        gcloud compute ssh danielventurini021@web-api-flask \
          --zone us-central1-a \
          --command "
            docker pull us-south1-docker.pkg.dev/venturini-brazil/flask-app/web-api:$BUILD_ID          
          "

images: ['us-south1-docker.pkg.dev/venturini-brazil/flask-app/web-api:$BUILD_ID']